name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Sync-Fork-action
        # You may pin to the exact commit or the version.
        # uses: XueMoMo/Sync-Fork-action@b1545dfaf057a7ba0e9c8987a5829ce176942995
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          # Token for accessing the remote repo with authentication
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          # Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action
          upstream_repository: pre-commit/pre-commit
          # Branch to sync from, e.g. => main, master, dev
          upstream_branch: master
          # Branch to push to, e.g. => main, master, prod
          target_branch: master
          # Any extra args to pass to `git checkout` like --recurse-submodules (only used when current branch is not target_branch), default = ""
          #git_checkout_args: # optional, default is 
          # Any extra args to pass to `git fetch` like --recurse-submodules, default = ""
          #git_fetch_args: # optional, default is 
          # How to print the list of new commits, default = --pretty=oneline
          #git_log_format_args: # optional, default is --pretty=oneline
          # Any extra args to pass to `git push` like --ff-only or --tags, default = ""
          git_pull_args: --tags
          # Any extra args to pass to `git push` like --force, default = ""
          git_push_args: --tags
          # Git user credentials for sigining commit (set to "null" for no credential changes)
          #git_user: # optional, default is Action - Fork Sync
          # Git email credentials for sigining commit (set to "null" for no credential changes)
          #git_email: # optional, default is action@github.com
          # Git config for "pull.rebase" (standard default to false, set to "null" for no config)
          #git_pull_rebase_config: # optional, default is false
                
